services:
  virushunter:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: virushunter_app
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./results:/app/results
    environment:
      - OLLAMA_BASE_URL=http://51.254.200.139:11434
      - OLLAMA_MODEL=llama3.2:1b
    restart: unless-stopped
    command: streamlit run app/streamlit_complete.py --server.port 8501 --server.address 0.0.0.0
